### ISSUE TITLE
Have a single command to run local smoketests for appservices functionality in Fenix

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2718]
Once we have the ability to [easily make a local build of appservices+Fenix](https://github.com/mozilla/application-services/issues/2691), we'll want to be able to easily smoketest that the appservices functionality in said build is actually working. I'd like to have a single command that I can run to verify this.

In the simplest case, being able to run `./gradlew test` could, as part of its test suite, make sure to exercise the core appservices features such as bookmarks, logins, and accounts integration.

Slightly more elaborately, perhaps we could have a `./gradlew testApplicationServices` command that runs a specific subset of tests that are known to relate to application-services functionality. This might mean they can run faster, which means they'll get run more often.

Even more elaborately, we could consider running the [Fenix Sync Integration Tests](https://docs.google.com/document/d/1dhxlbGQBA6aJi2Xz-CsJZuGJPRReoL7nfm9cYu4HcZI/), which are a kind of TPS-style test that actually launches the Fenix app, syncs some stuff from another machine, and verifies that it came through successfully.

Part of this bug is figuring out what approach to settle on. We'll know we can close this bug when we're comfortable replacing the manual testing instructions in our release process, with an instruction to run some automated testing command.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-877)
┆Story Points: 5
┆Epic: Automation and tooling to ensure that downstream integration of our releases is smooth and reliable
┆Sprint: SYNC - end 2020-04-10

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

From discussion with [~eoger@mozilla.com], I've edited the bug title here to emphasize these are local smoketests. We want to be able to run a single command to run a suite of smoketests locally against Fenix, but this bug is not about having them run automatically in CI or block PRs or anything like that. If I can replace the current process of "build fenix, launch it and click around a bit to see if everything still seems to be working" with "run this command" I will consider that a huge success.

**Comment by rfk** [comment]
I've prepared a set of 6 busted app-services PRs to help make this issue more concrete:

* [ ] Simulate a type mismatch in sync-manager FFI layer. [#2804]
* [ ] Simulate a missing symbol in the fxa-client build. [#2802]
* [ ] Simulate a problem with reading a bookmarks tree. [#2805]
* [ ] Simulate a problem with consumer integration of viaduct. [#2806]
* [ ] Simulate a problem with writing logins to disk. [#2807]
* [ ] Simulate architecture-specific missing symbols. [#2808]

We can close this issue when there's a documented very-small-number-of-steps procedure for running some Fenix tests against a local build of application-services, and said tests successfully reject each of the above busted PRs.

That might be running the Fenix testsuite itself, it might be running the [Fenix sync integration tests](https://docs.google.com/document/d/1dhxlbGQBA6aJi2Xz-CsJZuGJPRReoL7nfm9cYu4HcZI/), or it might be something else. Our task here is to select the right one, and to get any missing test coverage added.

**Comment by rfk** [comment]
>  Simulate a type mismatch in sync-manager FFI layer. [#2804]

Fenix test suite does not detect this. In fairness to Fenix I think this would be better detected either in an a-c unittest, or in an end-to-end functional test.

>  Simulate a missing symbol in the fxa-client build. [#2802]

Fenix test suite does not detect this. I don't think it ever load a live account object, instead mocking things out at the a-c level.

> Simulate a problem with reading a bookmarks tree. [#2805]

Fenix test suite does not detect this. There are a lot of bookmarks-related tests in there, but heavily mocked so they don't hit the appservices code. I wonder if we could make it easier to exercise a live bookmarks store for some or all of these tests, and whether consumers would actually want that.

> Simulate a problem with consumer integration of viaduct. [#2806]

Fenix test suite does not detect this. I think it's reasonable that unittests do not actually try to hit the network though.

> Simulate a problem with writing logins to disk. [#2807]

Fenix test suite does not detect this. I don't see a lot of test coverage in Fenix for passwords-related functionality, but then again, it seems to lean pretty heavily on behind-the-scenes integration between logins-store and Gecko that's provided by a-c.

> Simulate architecture-specific missing symbols. [#2808]

Fenix test suite does not detect this, but I wasn't expecting it to because they don't run on this specific architecture.

So that's none for six on running the Fenix unittest suite to detect possible integration issues.

**Comment by rfk** [comment]
We have this up and running now, although the tests haven't proven that useful for catching the kinds of bustage in the example broken PRs above. We can work towards exercising more of the live code over time, but for now, we don't have additional work we plan to pursue here. Closing.
