### ISSUE TITLE
Have a single command to run local smoketests for appservices functionality in android-components

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2719]
Our release process currently involves a manual verification step where we're supposed to build android-components against the candidate application-services release, run some of the sample apps, and re-assure ourselves that we didn't break anything. Let's figure out how to automate this.

In the simplest case, running `./gradlew test` in android-components could, as part of its test suite, make sure to exercise the core appservices features such as bookmarks, logins, and accounts. I'm told that Places does this already, but other appservices components may not have such coverage (particularly the ones that hit the network).

Slightly more elaborately, perhaps we could have a `./gradlew testApplicationServices` command that runs a specific subset of tests that are known to relate to application-services functionality. This might mean they can run faster, which means they'll get run more often; /cc @grigoryk.

Part of this bug is figuring out what approach to settle on. We'll know we can close this bug when we're comfortable replacing the manual testing instructions in our release process, with an instruction to run some automated testing command.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-878)
┆Story Points: 5
┆Epic: Automation and tooling to ensure that downstream integration of our releases is smooth and reliable
┆Sprint: SYNC - end 2020-04-10

**Comment by rfk** [comment]
I've prepared a set of 6 busted app-services PRs to help make this issue more concrete:

* [ ] Simulate a type mismatch in sync-manager FFI layer. [#2804]
* [ ] Simulate a missing symbol in the fxa-client build. [#2802]
* [ ] Simulate a problem with reading a bookmarks tree. [#2805]
* [ ] Simulate a problem with consumer integration of viaduct. [#2806]
* [ ] Simulate a problem with writing logins to disk. [#2807]
* [ ] Simulate architecture-specific missing symbols. [#2808]

We can close this issue when there's a documented very-small-number-of-steps procedure for running some android-components tests against a local build of application-services, and said tests successfully reject each of the above busted PRs.

This might involve running the android-components testsuite, or maybe it would involve some sample app that can run to exercise our core codepaths. We might also decide that running the [corresponding fenix tests](https://github.com/mozilla/application-services/issues/2718) will be sufficient in practice. Let's see what's possible.

**Comment by rfk** [comment]
The android-components subprojects that currently depend on appservices are:

* service-firefox-accounts
* feature-push
* support-migration
* support-rusthttp
* support-rustlog
* browser-storage-sync
* service-sync-logins
* support-sync-telemetry

So I'm using the below rather than running the full android-components test suite:

```
./gradlew service-firefox-accounts:test feature-push:test support-migration:test support-rusthttp:test support-rustlog:test browser-storage-sync:test service-sync-logins:test support-sync-telemetry:test
```

**Comment by rfk** [comment]
* [ ] Simulate a type mismatch in sync-manager FFI layer. [#2804]
    * All the above tests pass even with this bug in place.
* [ ] Simulate a missing symbol in the fxa-client build. [#2802]
    * All the above tests pass even with this bug in place.
* [x] Simulate a problem with reading a bookmarks tree. [#2805]
    * This one seems to be caught by an existing test, although it throws a `kotlin.KotlinNullPointerException` rather than a more nuanced error.
* [ ] Simulate a problem with consumer integration of viaduct. [#2806]
    * All the above tests pass even with this bug in place.
* [ ] Simulate a problem with writing logins to disk. [#2807]
    * All the above tests pass even with this bug in place.
* [ ] Simulate architecture-specific missing symbols. [#2808]
    * Unsurprisingly, this did not fail any tests when running on my desktop machine.

**Comment by rfk** [comment]
We have this up and running now, although the tests haven't proven that useful for catching the kinds of bustage in the example broken PRs above. We will work incrementally towards having the android-components tests exercise more live app-services code in future (e.g. new logins work will use a live in-memory test database) so I expect the value here to grow slowly over time.  For now we don't have any more concrete work we plan to do in this bug, so closing.
