### ISSUE TITLE
Have a single command to run local smoketests for appservices functionality in Firefox for iOS

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2720]
Once we have the ability to [easily make a local build of appservices+firefox-ios](https://github.com/mozilla/application-services/issues/2717), we'll want to be able to easily smoketest that the appservices functionality in said build is actually working. I'd like to have a single command that I can run to verify this.

In the simplest case, running the tests for the firefox-ios repo should make sure to exercise the core appservices features such as bookmarks, logins, and accounts integration using live component code (rather than e.g. mocks).

More elaborately, we could consider running the [iOS Sync Integration Tests](https://docs.google.com/document/d/1dhxlbGQBA6aJi2Xz-CsJZuGJPRReoL7nfm9cYu4HcZI/), which are a kind of TPS-style test that actually launches the app, syncs some stuff from another machine, and verifies that it came through successfully.

Part of this bug is figuring out what approach to settle on. We'll know we can close this bug when we're comfortable adding instructions to run this test command to our release process docs, and feel confident that it would catch sufficiently-critical integration issues.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-879)
┆Story Points: 5
┆Epic: Integration testing for a-s
┆Sprint: SYNC - end 2020-04-10

**Comment by rfk** [comment]
I've prepared a set of 6 busted app-services PRs to help make this issue more concrete:

* [ ] Simulate a type mismatch in sync-manager FFI layer. [#2804]
* [ ] Simulate a missing symbol in the fxa-client build. [#2802]
* [ ] Simulate a problem with reading a bookmarks tree. [#2805]
* [ ] Simulate a problem with consumer integration of viaduct. [#2806]
* [ ] Simulate a problem with writing logins to disk. [#2807]
* [ ] Simulate architecture-specific missing symbols. [#2808]

We can close this issue when there's a documented very-small-number-of-steps procedure for running some Firefox for iOS tests against a local build of application-services, and said tests successfully reject each of the above busted PRs.

That might be running the firefox-ios testsuite itself, it might be running the [ios sync integration tests](https://docs.google.com/document/d/1dhxlbGQBA6aJi2Xz-CsJZuGJPRReoL7nfm9cYu4HcZI/), or it might be something else. Our task here is to select the right one, and to get any missing test coverage added.

**Comment by rfk** [comment]
I'm testing this out using our [instructions for local dev with iOS](https://github.com/mozilla/application-services/blob/master/docs/howtos/locally-published-components-in-ios.md), and the following command to run the tests from a console window:

```
xcodebuild test -project Client.xcodeproj -scheme Fennec -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3'
```

Early results (none of which are really a surprise):

* ~~Simulate a type mismatch in sync-manager FFI layer. [#2804]~~
    * Tests pass, but that's expected, because iOS doesn't yet use the syncmanager.
* [x] Simulate a missing symbol in the fxa-client build. [#2802]
    * Fails a build error about the missing symbol.
* [ ] Simulate a problem with reading a bookmarks tree. [#2805]
    * Fails, due to test `StorageTests:TestSQLiteHistory.testDomainUpgrade()`
    * I will take a bit of a look at this test and see if it's catching this on purpose, or by accident.
* [ ] Simulate a problem with consumer integration of viaduct. [#2806]
    * Fails, due to test `StorageTests:TestSQLiteHistory.testDomainUpgrade()`
    * But I'm kind of surprised about this and need to dig in to why
* [x] Simulate a problem with writing logins to disk. [#2807]
    *  Fails, due to `RustLoginsTests.testUpdateLogin()`
* ~~Simulate architecture-specific missing symbols. [#2808]~~
    * Tests pass, but that's expected, because iOS doesn't use that architecture.

So overall just running the iOS tests from the command-line seems to be pretty good at detecting integration issues in appservices!

**Comment by rfk** [comment]
This was closed by the above PR but I'm going to re-open it to continue looking at the "what bustage might we have caught downstream?" checklist.

**Comment by rfk** [comment]
> Fails, due to test StorageTests:TestSQLiteHistory.testDomainUpgrade()

I've convinced myself that the things that failed on this test, were doing so for unrelated reasons, since I also got occasional test failures from this on master.

**Comment by rfk** [comment]
Filed a follow-up bug here to consider adding some bookmarks smoketests in the firefox-ios repo:

  https://github.com/mozilla-mobile/firefox-ios/issues/6384

**Comment by rfk** [comment]
I submitted a PR to add smoketests to our release process here:

  https://github.com/mozilla/application-services/pull/2916

I don't have any other concrete followups coming out of this bug. I was hoping to be able to integrate the [iOS Sync Integration Tests](https://docs.google.com/document/d/1dhxlbGQBA6aJi2Xz-CsJZuGJPRReoL7nfm9cYu4HcZI/) into this procedure, but I haven't been able (yet) to get them running reliably enough to be comfortable doing so.  These tests do run in automation for firefox-ios and so they'll still help us catch integration problems, just after the fact of an a-s release.
