### ISSUE TITLE
[Meta] Remove SQLCipher from Logins engine

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#5777]
### Context
SQLCipher was phased out of application-services in September 2021 [[Relevant ADR](https://github.com/mozilla/application-services/blob/main/docs/adr/0001-update-logins-api.md)]. It used to provide full-db encryption but we have since moved to per-field encryption. After nearly two years, we can safely remove SQLCipher as the majority of users have migrated.

It is estimated we're near a point we can safely remove the migration path. Removing SQLCipher will allow some benefits (smaller binary, simpler compilation, building iOS simulator for M1). 

## Steps for removal
* [ ] Remove migration path from iOS
* [ ] Remove migration path from Android
* [ ] remove lib/references to it in a-s

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3875)
┆Epic: Removal of SQLCipher
