### ISSUE TITLE
[meta] PlacesAPI History deletion APIs

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#621]
This is quite nuanced, @thomcc and @mhammond will know the fine and scary details (please edit this issue as you see fit!).

These APIs will likely function somewhat differently for synced and non-synced users. Not all of PlacesAPI users are going to be also Sync users, so that's an important distinction to keep in mind.

Some starter reading material is found here: https://github.com/mozilla/application-services/issues/317#issuecomment-458371812.

At the high level, consumers will want to have APIs to:
- [x] Delete all history
- [x] Delete specific page visits from history (e.g. what's behind a "delete" button in the recent history UI)
- [x] Delete visits in a time range (optional, currently not part of Fenix mocks)

Related is the prunning API, except they it's not directly powering user-accessible functionality. See https://github.com/mozilla/application-services/issues/611.

**Comment by thomcc** [comment]
We give Delete All Since X, which covers delete all (although maybe we want to optimize for this case in the future).

**Comment by thomcc** [comment]
> Delete specific page visits from history (e.g. what's behind a "delete" button in the recent history UI)

The plan here is to add a table for deleted visits, to prevent readdition. That or a boolean flag to moz_historyvisits (The flag is probably cheaper, and given how SQLite works, always empty columns shouldn't take up much space... Hm...).

**Comment by mhammond** [comment]
> We give Delete All Since X, which covers delete all (although maybe we want to optimize for this case in the future).

Yeah, I don't think we should `deleteAll` via `delete_since(0)` as it is suboptimal for both sync and non-sync users. I think @davismtl and Ryan Feeley are discussing this from Sync's POV, but IMO, a sync user wanting to "delete all history" probably also means "and disconnect this device from sync" rather than "and also delete all history from all of my devices".

For non-sync users (and sync users notwithstanding the above), it's almost certainly possible to have a more performant API for `deleteAll` than `delete_since(0)`.

Thom also mentioned there was a requirement to delete a single specific visit (ie, delete a visit given a URL and an exact timestamp of the visit). @grigoryk, is this requirement supposed to be captured here too?

**Comment by thomcc** [comment]
It is, as "Delete specific page visits from history"

**Comment by mhammond** [comment]
Is there a "delete page" requirement?

**Comment by thomcc** [comment]
IIUC, not at the moment.

**Comment by thomcc** [comment]
This is done.
